### PR TITLE
Test elastic scroll view

### PR DESCRIPTION
**Pull request by andyque**

### CODE REVIEW

**Comment by andyque** [comment]
@neokim  Because there are merge conflicts in your PR. So I merged upstream to your PR. 
And in this PR, I also do some cleanup. You could just refer to `UIScrollView.h` and `UIScrollView.cpp` for more information. 
Thanks.

**Comment by andyque** [comment]
@neokim  All I have done to your PR is https://github.com/andyque/cocos2d-x/commit/30d2129f0c162e6a961d28698df645f17d34763a

**Comment by neokim** [comment]
@andyque I've merged your PR but `cocos2d_tests` Xcode project fails to compile in `CCAutoPolygon.cpp` line 32 complaining it cannot find `'clipper/clipper.hpp'`. Something wrong?

**Comment by andyque** [comment]
@neokim  you should call `python download-deps.py` in /path/to/cocos2d-x/ to download the new dependency.

**Comment by andyque** [comment]
@neokim  Before doing the operation above, you should also call `git submodule update` to update all the submodules.

**Comment by neokim** [comment]
@andyque Thank you! It works nicely.

**Pull request merged**
